version: v1beta
component:
  splitter-txt:
    type: text
    task: TASK_CHUNK_TEXT
    input:
      strategy:
        setting:
          chunk-method: Recursive
          chunk-overlap: ${variable.chunk_overlap}
          chunk-size: ${variable.max_chunk_length}
          keep-separator: false
          model-name: gpt-4
      text: ${variable.text_input}
variable:
  chunk_overlap:
    title: chunk-overlap
    description: number of tokens that overlap between consecutive chunks
    type: number
    instill-ui-order: 2
  max_chunk_length:
    title: max-chunk-length
    description: splitting maximum tokens size
    type: number
  text_input:
    title: text-input
    type: string
    instill-ui-order: 1
    instill-ui-multiline: true
output:
  input_token_count:
    title: input-token-count
    value: ${splitter-txt.output.token-count}
    instill-ui-order: 1
  output_chunks_count:
    title: output_chunks_count
    value: ${splitter-txt.output.chunk-num}
    instill-ui-order: 2
  split_result:
    title: split-result
    value: ${splitter-txt.output.text-chunks}
