version: v1beta
component:
  splitter-md:
    type: text
    task: TASK_CHUNK_TEXT
    input:
      strategy:
        setting:
          chunk-method: Markdown
          chunk-overlap: ${variable.chunk_overlap}
          chunk-size: ${variable.max_chunk_length}
          code-blocks: true
          model-name: gpt-4
      text: ${variable.md_input}
variable:
  chunk_overlap:
    title: chunk-overlap
    description: number of tokens that overlap between consecutive chunks
    format: number
  max_chunk_length:
    title: max-chunk-length
    description: splitting maximum tokens size
    format: number
    instill-ui-order: 2
  md_input:
    title: md-input
    description: original extracted markdown text (single source of truth)
    format: string
    instill-ui-order: 1
    instill-ui-multiline: true
output:
  input_token_count:
    title: input-token-count
    value: ${splitter-md.output.token-count}
    instill-ui-order: 1
  output_chunks_count:
    title: output-chunks-count
    value: ${splitter-md.output.chunk-num}
    instill-ui-order: 2
  split_result:
    title: split-result
    value: ${splitter-md.output.text-chunks}
