ARG GOLANG_VERSION=1.24.6
FROM golang:${GOLANG_VERSION}-bullseye

ARG SERVICE_NAME SERVICE_VERSION

WORKDIR /${SERVICE_NAME}

# -- DinD

COPY --from=docker:dind-rootless --chown=nobody:nogroup /usr/local/bin/docker /usr/local/bin

# -- install 3rd-party

ARG TARGETOS TARGETARCH K6_VERSION XK6_VERSION XK6_SQL_VERSION XK6_SQL_POSTGRES_VERSION

# air
RUN --mount=target=. --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg GOOS=$TARGETOS GOARCH=$TARGETARCH go install github.com/cosmtrek/air@v1.49.0

# grpcurl
RUN --mount=target=. --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg GOOS=$TARGETOS GOARCH=$TARGETARCH go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest

# k6
RUN --mount=target=. --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg GOOS=$TARGETOS GOARCH=$TARGETARCH go install go.k6.io/xk6/cmd/xk6@v${XK6_VERSION}
RUN --mount=target=. --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg GOOS=$TARGETOS GOARCH=$TARGETARCH xk6 build v${K6_VERSION} \
    --with github.com/grafana/xk6-sql@v${XK6_SQL_VERSION} \
    --with github.com/grafana/xk6-sql-driver-postgres@v${XK6_SQL_POSTGRES_VERSION} \
    --with github.com/grafana/xk6-exec@latest \
    --output /usr/bin/k6

# MinIO Client (mc) for integration tests to verify blob storage
RUN curl -fsSL https://dl.min.io/client/mc/release/linux-${TARGETARCH}/mc -o /usr/bin/mc && \
    chmod +x /usr/bin/mc

# Milvus CLI for integration tests to verify vector storage
# Install Python 3 and pip if not already installed
# Also install GNU parallel for running tests in parallel
RUN apt-get update && apt-get install -y python3 python3-pip parallel && rm -rf /var/lib/apt/lists/*
# Install pymilvus
RUN pip3 install pymilvus>=2.4.3

# -- set up Go
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN chown -R nobody:nogroup /go
ENV GOCACHE=/go/.cache/go-build
ENV GOENV=/go/.config/go/env

ENV SERVICE_NAME=${SERVICE_NAME}
ENV SERVICE_VERSION=${SERVICE_VERSION}

USER nobody:nogroup

ENTRYPOINT ["tail", "-f", "/dev/null"]
