server:
  privateport: 3082
  publicport: 8082
  https:
    cert:
    key:
  edition: docker-ce:dev
  usage:
    enabled: true
    tlsenabled: true
    host: usage.instill-ai.com
    port: 443
  debug: true
  maxdatasize: 1024 # MB in unit
  workflow:
    maxworkflowtimeout: 3600 # in seconds
    maxworkflowretry: 1
    maxactivityretry: 3
  instillcorehost: http://localhost:8080
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: artifact
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
influxdb:
  url: http://influxdb:8086
  token: i-love-instill-ai
  org: instill-ai
  bucket: instill-ai
  flushinterval: 10 # In seconds for non-blocking batch mode
  https:
    cert:
    key:
cache:
  redis:
    redisoptions:
      addr: redis:6379
otelcollector:
  enable: false
  host: otel-collector
  port: 4317
temporal:
  hostport: temporal:7233
  namespace: instill-core
  retention: 1d
  metricsport: 8096
  apikey:
  insecureskipverify:
mgmtbackend:
  host: mgmt-backend
  publicport: 8084
  privateport: 3084
  https:
    cert:
    key:
pipelinebackend:
  host: pipeline-backend
  publicport: 8081
  privateport: 3081
  https:
    cert:
    key:
modelbackend:
  host: model-backend
  publicport: 8083
  privateport: 3083
  namespace: admin
  https:
    cert:
    key:
registry:
  host: registry
  port: 5000
openfga:
  host: openfga
  port: 8081
minio:
  host: minio
  port: 9000
  user: minioadmin
  password: minioadmin
  bucketname: core-artifact
milvus:
  host: milvus
  port: 19530
blob:
  hostport: http://localhost:8080
