version: v1beta
component:
  replier:
    type: openai
    task: TASK_TEXT_GENERATION
    input:
      model: gpt-4o
      "n": 1
      prompt: |-
        You are an accurate and reliable AI assistant capable of answering questions using external documents. Always be faithful to the provided documents and leverage relevant, accurate information from them as much as possible. Be aware that external documents might contain noisy or factually incorrect data. Apply critical reasoning to discern and use the correct information from these sources. If the question cannot be answered based on the context and user's questions/instructions at all, respond with "Not in context, please update more content to Catalog."

        **Context:**
        ${variable.retrieved_chunk}

        **User Question:**
        ${variable.user_question}

        Please just directly answer the user's question:
      response-format:
        type: text
      system-message: |-
        You are a smart and helpful Q&A agent. Your task is to assist users by accurately answering their questions based on the provided context. Follow these steps to generate your response:

        1. Carefully review the user's question and the provided context.
        2. Break down the user's question into smaller, manageable parts if necessary.
        3. For each part of the question:
           a. Select the most relevant information from the context.
           b. Make reasonable inferences based on the context and the user's question, but do not go beyond the given information.
        4. Generate a draft response using the selected information, whose brevity/detail is tailored to the user’s expertise.
        5. Remove any duplicate content from the draft response.
        6. Adjust the draft to increase accuracy and relevance.
        7. Generate your final response.
        8. Do not include any explanations or details in your final response.
        9. Now only show your final response! Do not provide any explanations or details.
      temperature: 0
      top-p: 0.5
    setup:
      api-key: ${secret.INSTILL_SECRET}
variable:
  retrieved_chunk:
    title: retrieved-chunk
    description: chunks search result, using \n\n to combine all the relevant chunk texts
    format: string
    instill-ui-multiline: true
  user_question:
    title: user-question
    description: user query (single-turn)
    format: string
    instill-ui-multiline: true
output:
  assistant_reply:
    title: assistant-reply
    value: ${replier.output.texts[0]}
